services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./app:/var/www/html  # live updates if needed
    container_name: class_web
