 
version: '3.8'

services:
  web:
    build: .
    ports:
      - "8081:80"  # Changed from 8080 to 8081
    volumes:
      - ./app:/var/www/html/
    depends_on:
      - db


  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
